Added some user services
KeithSantamaria/CHOGAN pull request #54
Opened 2021-06-04 16:00 UTC by mfong5

Please leave a comment if you think any other methods should be added.

2021-06-04 16:16 UTC, encperez submitted a review, later dismissed

2021-06-04 16:18 UTC, KeithSantamaria requested changes
The function ideas are good, alter them to take in users and write to a local instance of db

see example on discord as reference or contact other members of team for reference

2021-06-06 23:44 UTC, KeithSantamaria approved these changes
Looks good, we should make sure we update everyone that the user model slightly changed, and there is a potential for the db name to be forced to change as well, but other wise this looks workable

2021-06-07 03:03 UTC, encperez approved these changes

2021-06-07 03:03 UTC, merged